steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Auto Release on Version Bump
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}


refer to this expand this: https://github.com/softprops/action-gh-release