steps:
  - name: Checkout Repository
    uses: actions/checkout@v
  - name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '16'
  - name: Install Dependencies
    run: npm instal
  - name: Run Tests
    run: npm test
